"""empty message

Revision ID: 4b3550048a35
Revises: ac63f8d2cfe9
Create Date: 2023-10-25 15:25:46.072366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b3550048a35'
down_revision = 'ac63f8d2cfe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadfile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_files', sa.String(length=200), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadfile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('sub_files')

    # ### end Alembic commands ###
