"""empty message

Revision ID: 7e6d358e908d
Revises: 89d7be831815
Create Date: 2024-01-27 15:53:41.267232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e6d358e908d'
down_revision = '89d7be831815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segmentationfile', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segmentationfile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
