"""empty message

Revision ID: 82d8050e8337
Revises: 4b3550048a35
Create Date: 2023-10-25 16:38:59.670838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d8050e8337'
down_revision = '4b3550048a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadfile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadfile', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
