"""empty message

Revision ID: b75f2f1156d1
Revises: eccc9f3b91cc
Create Date: 2023-11-11 18:01:31.323867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b75f2f1156d1'
down_revision = 'eccc9f3b91cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classificationfile', schema=None) as batch_op:
        batch_op.alter_column('classification_result',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=400),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classificationfile', schema=None) as batch_op:
        batch_op.alter_column('classification_result',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
