"""empty message

Revision ID: e929142d43e6
Revises: 7e6d358e908d
Create Date: 2024-01-27 15:54:37.423537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e929142d43e6'
down_revision = '7e6d358e908d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segmentationfile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=False))

    with op.batch_alter_table('uploadfile', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadfile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=100), nullable=False))

    with op.batch_alter_table('segmentationfile', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
