"""empty message

Revision ID: eccc9f3b91cc
Revises: 0ef0d14abb29
Create Date: 2023-11-11 17:23:37.864105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eccc9f3b91cc'
down_revision = '0ef0d14abb29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classificationfile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_images_sequence', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('original_images_path', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classificationfile', schema=None) as batch_op:
        batch_op.drop_column('original_images_path')
        batch_op.drop_column('original_images_sequence')

    # ### end Alembic commands ###
